---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-lb-operator
  template:
    metadata:
      labels:
        name: nginx-lb-operator
    spec:
      serviceAccountName: nginx-lb-operator
      containers:
        - name: nginx-lb-operator
          # Replace this with the built image name
          image: "REPLACE_IMAGE"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nginx-lb-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_DEBUG_LOGS
              value: "False"
            - name: ANSIBLE_VERBOSITY_APPLICATION_LB_NGINX_COM
              value: "1"
            - name: WORKER_APPLICATION_LB_NGINX_COM
              value: "1"
            - name: ANSIBLE_VERBOSITY_CERTIFICATE_LB_NGINX_COM
              value: "1"
            - name: WORKER_CERTIFICATE_LB_NGINX_COM
              value: "1"
            - name: ANSIBLE_VERBOSITY_COMPONENT_LB_NGINX_COM
              value: "1"
            - name: WORKER_COMPONENT_LB_NGINX_COM
              value: "1"
            - name: ANSIBLE_VERBOSITY_CONTROLLER_LB_NGINX_COM
              value: "1"
            - name: WORKER_CONTROLLER_LB_NGINX_COM
              value: "1"
            - name: ANSIBLE_VERBOSITY_GATEWAY_LB_NGINX_COM
              value: "1"
            - name: WORKER_GATEWAY_LB_NGINX_COM
              value: "1"
            - name: ANSIBLE_VERBOSITY_DEPLOYMENT_APPS
              value: "1"
            - name: WORKER_DEPLOYMENT_APPS
              value: "1"
      volumes:
        - name: runner
          emptyDir: {}
