= Operator Demo
:showtitle:
:toc: left

== Prerequisites

The manifests in this demo will create a namespace called `simple-ingress-demo` on your Kubernetes cluster
and deploy containers from Docker Hub. The containers are:

* tuxinvader/nginx-lb-operator:latest - A build of the nginx-lb-operator
* tuxinvader/whatcheese-web:latest - A simple demo website
* tuxinvader/whatcheese-db:latest - A MySQL Database
* tuxinvader/whatcheese-api:latest - A Simple Cheese

All you need besides a Kubernetes cluster is a NGINX Controller and an NGINX Plus instance

== The Demo Site

The demo site is called WhatCheese, it has a few simple web pages, and a Cheese API. 
By default the NGINX Instance will be configured to host pages at `*.whatcheese.nginx.demo`
on both HTTP and HTTPS. If you want to change the hostname, then modify manifest `50-gateway.yaml`

== Install the CRDs

If you haven't done so already you will need to install the `Custom Resource Definitions` for the
Operator. The CRDs can be found from the root of this repository in the deploy directory.

----
kubectl create -f deploy/crds/lb.nginx.com_controllers_crd.yaml
kubectl create -f deploy/crds/lb.nginx.com_applications_crd.yaml
kubectl create -f deploy/crds/lb.nginx.com_certificates_crd.yaml
kubectl create -f deploy/crds/lb.nginx.com_components_crd.yaml
kubectl create -f deploy/crds/lb.nginx.com_gateways_crd.yaml
----

== The Manifests

The manifests are numbered in the order in which they should be applied. First create the demo namespace
and the service account and role bindings, and then deploy the operator.

----
kubectl apply -f 01-namespace.yaml
kubectl apply -f 02-role-bindings.yaml
kubectl apply -f 03-operator.yaml
----

Next deploy the whatcheese services: the website, the database, and the API

----
kubectl apply -f 10-whatcheese-web.yaml
kubectl apply -f 11-whatcheese-db.yaml
kubectl apply -f 12-whatcheese-api.yaml
----

You will need to modify manifest `20-controller-secret.yaml` and replace the `user_password` secret with
a base64 encoded version of your password. Eg:

----
echo YourControllerPassword | base64
----

Then modify `21-controller.yaml` to have the details for your controller. That is the user_email who's
password you have just encoded above, and the FQDN of the controller, and the Environment which the user
has write permissions.

Once modified, apply them

----
kubectl apply -f 20-controller-secret.yaml
kubectl apply -f 21-controller.yaml
----

You can now apply the rest of the manifests in order to deploy the Application components onto your controller.

You will need to check that the `instanceRef` in `50-gateway.yaml` matches the NGINX Instance ID where you want
the config deployed. You may change the hostname of the service in this file too if you wish.

When you get to the `60-component-whatcheese*` manifest, you can chose to deploy with or without App Protect,
depending on if you have the AP WAF module installed on your NGINX Plus instance.

Enjoy.


